# This rule is not used by the project playground-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the view.ystkfujii.github.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: playground-operator
    app.kubernetes.io/managed-by: kustomize
  name: markdownview-editor-role
rules:
- apiGroups:
  - view.ystkfujii.github.io
  resources:
  - markdownviews
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - view.ystkfujii.github.io
  resources:
  - markdownviews/status
  verbs:
  - get
