---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - view.ystkfujii.github.io
  resources:
  - appdeployers
  - markdownviews
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - view.ystkfujii.github.io
  resources:
  - appdeployers/finalizers
  - markdownviews/finalizers
  verbs:
  - update
- apiGroups:
  - view.ystkfujii.github.io
  resources:
  - appdeployers/status
  - markdownviews/status
  verbs:
  - get
  - patch
  - update
