apiVersion: view.ystkfujii.github.io/v1
kind: AppDeployer
metadata:
  labels:
    app.kubernetes.io/name: playground-operator
    app.kubernetes.io/managed-by: kustomize
  name: appdeployer-sample-1
spec:
  serviceAccountName: appdeployer-sample-2
  deployment:
    replicas: 2
    imageName: "nginx:1.27-alpine"
